Update index.html to fix invalid axios digest
salesforce-misc/byoc-ott-demo-app pull request #14
Opened 2024-02-28 05:59 UTC by james-wang-sfdc

2024-02-28 06:02 UTC, james-wang-sfdc commented on src/index.html
> -    <script src="https://unpkg.com/axios/dist/axios.min.js" integrity="sha384-FJRdIAsgR2MYwYL0h2EFW4mafJe48IRnaL0OuRmColRwwvr4nFhW13m/HbjmD3v8" crossorigin="anonymous"></script>
Remove unnecessary integrity attribute in <script>

2024-02-28 23:18 UTC, denam requested changes

2024-02-29 01:13 UTC, james-wang-sfdc commented on src/index.html
> -    <script src="https://unpkg.com/axios/dist/axios.min.js" integrity="sha384-FJRdIAsgR2MYwYL0h2EFW4mafJe48IRnaL0OuRmColRwwvr4nFhW13m/HbjmD3v8" crossorigin="anonymous"></script>
Good catch!

2024-02-29 20:41 UTC, dlouvton approved these changes

2024-02-29 21:09 UTC, merged